name: 📊 Executive Level Long Running Task
description: Track strategic initiatives and long-term projects for early-stage, innovative ventures
title: "[INITIATIVE]: "
labels: ["executive", "strategic", "long-running"]
body:
  - type: markdown
    attributes:
      value: |
        ## Executive Level Initiative
        This template is for tracking strategic, long-term initiatives in early-stage, innovative projects.
        Suitable for mobile app development, finding partners, business planning, and technology evaluation.
        
  - type: input
    id: initiative-name
    attributes:
      label: Initiative Name
      description: Short, descriptive name for this initiative
      placeholder: "Mobile App MVP Development or Partner Acquisition Q1 2024"
    validations:
      required: true
      
  - type: dropdown
    id: initiative-type
    attributes:
      label: Initiative Type
      description: What type of initiative is this?
      options:
        - Product Development (Mobile App)
        - Technology Evaluation & Selection
        - Partner & Resource Acquisition
        - Business Plan Development
        - Market Research & Validation
        - Fundraising & Investment
        - Infrastructure Setup
        - Team Building & Recruitment
        - Strategic Initiative
        - Other
      default: 0
    validations:
      required: true
      
  - type: textarea
    id: executive-summary
    attributes:
      label: Executive Summary
      description: High-level overview of the initiative and its strategic importance
      placeholder: "This initiative aims to..."
    validations:
      required: true
      
  - type: textarea
    id: business-objectives
    attributes:
      label: Business Objectives
      description: What are the key business objectives this initiative will achieve?
      placeholder: |
        Examples for early-stage projects:
        1. Complete mobile app MVP with core features by [date]
        2. Identify and onboard 3 technical partners/contractors
        3. Validate business model with 100 potential customers
        4. Secure seed funding of $XXX,XXX
        5. Launch beta version to first 50 users
    validations:
      required: true
      
  - type: textarea
    id: scope
    attributes:
      label: Scope
      description: Define what is included and excluded from this initiative
      placeholder: |
        **In Scope:**
        - Item 1
        - Item 2
        
        **Out of Scope:**
        - Item 1
        - Item 2
    validations:
      required: true
      
  - type: textarea
    id: key-stakeholders
    attributes:
      label: Key Stakeholders & Partners
      description: Who are the key stakeholders, team members, and potential partners?
      placeholder: |
        **Internal Team:**
        - Founder/CEO: @username
        - Technical Lead: @username or [To Be Hired]
        - Business Development: @username
        
        **Partners & Resources:**
        - Mobile Development Partner: [Searching/Identified/Contracted]
        - Backend Development: [In-house/Partner/TBD]
        - Design Resources: [Freelancer/Agency/TBD]
        
        **Advisors/Mentors:**
        - Technical Advisor: [Name/TBD]
        - Business Advisor: [Name/TBD]
    validations:
      required: true
      
  - type: input
    id: start-date
    attributes:
      label: Start Date
      description: When does/did this initiative begin?
      placeholder: "YYYY-MM-DD"
    validations:
      required: true
      
  - type: input
    id: target-completion
    attributes:
      label: Target Completion Date
      description: When is this initiative expected to complete?
      placeholder: "YYYY-MM-DD"
    validations:
      required: true
      
  - type: textarea
    id: budget
    attributes:
      label: Budget & Resources
      description: Budget allocation and resource requirements for early-stage venture
      placeholder: |
        **Budget Breakdown:**
        - Mobile App Development: $XX,XXX (contractor/agency)
        - Backend Infrastructure: $X,XXX/month (cloud services)
        - Design & UX: $X,XXX
        - Marketing/Customer Acquisition: $X,XXX
        - Legal & Compliance: $X,XXX
        - Total Initial Budget: $XXX,XXX
        
        **Resource Needs:**
        - Full-time: X people
        - Part-time/Contractors: X people
        - Technical partners: [list needs]
        - Funding status: [Bootstrapped/Seeking/Secured]
    validations:
      required: false
      
  - type: textarea
    id: milestones
    attributes:
      label: Key Milestones
      description: Major milestones and checkpoints for early-stage project
      placeholder: |
        - [ ] Technology Stack Selection - Target: YYYY-MM-DD
        - [ ] Partner/Contractor Onboarding - Target: YYYY-MM-DD
        - [ ] Mobile App MVP Development - Target: YYYY-MM-DD
        - [ ] Backend Infrastructure Setup - Target: YYYY-MM-DD
        - [ ] Beta Launch - Target: YYYY-MM-DD
        - [ ] First Customer Acquisition - Target: YYYY-MM-DD
        - [ ] Business Plan Completion - Target: YYYY-MM-DD
        - [ ] Funding Round Close - Target: YYYY-MM-DD
    validations:
      required: true
      
  - type: textarea
    id: success-criteria
    attributes:
      label: Success Criteria & KPIs
      description: How will success be measured for this early-stage initiative?
      placeholder: |
        **Product KPIs:**
        - Mobile app functionality: X core features completed
        - App performance: < X seconds load time
        - Platform coverage: iOS and/or Android
        
        **Business KPIs:**
        - User acquisition: X beta users
        - Customer validation: X interviews/surveys completed
        - Partnership: X partners/contractors secured
        - Funding: $XXX,XXX raised
        
        **Technical KPIs:**
        - Technology evaluation: X platforms assessed
        - Development velocity: X story points per sprint
        - Code quality: X% test coverage
    validations:
      required: true
      
  - type: textarea
    id: risks
    attributes:
      label: Key Risks & Dependencies
      description: Major risks and dependencies for early-stage project
      placeholder: |
        **Risks:**
        - Technical: Mobile platform choice may limit features [Mitigation: Multi-platform strategy]
        - Resource: Difficulty finding qualified developers [Mitigation: Multiple recruitment channels]
        - Financial: Budget overrun on development [Mitigation: Phased approach, MVP focus]
        - Market: Product-market fit not validated [Mitigation: Early customer discovery]
        - Partnership: Key partner delays delivery [Mitigation: Backup options identified]
        
        **Dependencies:**
        - Technology evaluation must complete before development starts
        - Backend infrastructure needed before mobile app integration
        - Partner contracts must be signed before work begins
        - Business plan required for fundraising activities
    validations:
      required: false
      
  - type: textarea
    id: status-updates
    attributes:
      label: Status Updates
      description: Regular status updates will be added here as comments
      placeholder: |
        This section is for tracking progress. Please add status updates as comments on this issue.
        
        **Status Update Template:**
        - Date: YYYY-MM-DD
        - Overall Status: 🟢 On Track / 🟡 At Risk / 🔴 Off Track
        - Progress: [brief summary]
        - Achievements: [completed items]
        - Next Steps: [upcoming activities]
        - Issues/Blockers: [current challenges]
    validations:
      required: false
      
  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: Strategic priority level
      options:
        - P0 - Critical (Board Level)
        - P1 - High (Executive Level)
        - P2 - Medium (Department Level)
        - P3 - Low (Team Level)
      default: 1
    validations:
      required: true
      
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Any additional information, documents, or references
      placeholder: Links to strategic documents, market research, etc.
    validations:
      required: false
