name: 💡 Feature Request
description: Suggest a new feature or enhancement
title: "[FEATURE]: "
labels: ["enhancement", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        ## Feature Request
        Thank you for suggesting a new feature! Please provide as much detail as possible.
        
  - type: textarea
    id: problem-statement
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? Is your feature request related to a problem?
      placeholder: "I'm always frustrated when..."
    validations:
      required: true
      
  - type: textarea
    id: proposed-solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see
      placeholder: "I would like to see..."
    validations:
      required: true
      
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternative solutions or features?
      placeholder: "I've also thought about..."
    validations:
      required: false
      
  - type: textarea
    id: use-cases
    attributes:
      label: Use Cases
      description: Describe specific use cases for this feature
      placeholder: |
        1. Use case 1: [description]
        2. Use case 2: [description]
    validations:
      required: false
      
  - type: textarea
    id: benefits
    attributes:
      label: Expected Benefits
      description: What benefits will this feature provide?
      placeholder: |
        - Improved efficiency
        - Better user experience
        - Cost reduction
    validations:
      required: false
      
  - type: textarea
    id: mockups
    attributes:
      label: Mockups/Examples
      description: Add any mockups, screenshots, or examples that help illustrate the feature
      placeholder: Drag and drop images here or provide links
    validations:
      required: false
      
  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Nice to have
        - Important
        - Critical
      default: 0
    validations:
      required: true
      
  - type: dropdown
    id: willing-to-contribute
    attributes:
      label: Willing to Contribute
      description: Are you willing to help implement this feature?
      options:
        - "Yes"
        - "No"
        - "Maybe"
      default: 2
    validations:
      required: false
      
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context about the feature request here
      placeholder: Any additional information
    validations:
      required: false
